name: summarize_it
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.3
  google_generative_ai: ^0.4.3
  pdf_image_renderer: ^0.7.0
  file_picker: ^8.0.6
  rounded_loading_button_plus: ^3.0.1
  fading_edge_scrollview: ^4.1.1
  flutter_lyric: ^2.0.4+6
  gap: ^3.0.1
  http: ^1.2.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/tab_box/
    - assets/icons/
    - .env

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic